# Generated by Django 4.2.7 on 2023-11-09 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msistore', '0003_rename_isprereview_image_ispreview_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='isPreview',
            new_name='is_Preview',
        ),
    ]
