# Generated by Django 4.2.7 on 2023-11-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msistore', '0006_alter_image_is_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='is_Preview',
            new_name='preview',
        ),
    ]
