# Generated by Django 4.2.7 on 2023-11-17 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msistore', '0008_order_statusorder_orderitem_order_products_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(null=True, through='msistore.OrderItem', to='msistore.product'),
        ),
    ]
