# Generated by Django 4.2.7 on 2023-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msistore', '0011_alter_order_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(default=[], null=True, through='msistore.OrderItem', to='msistore.product'),
        ),
    ]
