# Generated by Django 4.2.7 on 2024-01-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msistore', '0013_alter_order_products_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_order', to='msistore.order'),
        ),
    ]
